config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root to: 'pages#home'
    end

    unauthenticated :user do
      root to: "devise/sessions#new"
    end
  end

  # root to: get 'sign_in', :to =>

  # devise_scope :user do
  #   get "/users/sign_in" => "registrations#new"
  # end

  #   root to: "devise/sessions#new"
   # root to:
  # root to: 'devise/registrations#new'

  resources :games, only: [:show, :index] do
    resources :comments, only: :create

    resources :likes, only: [:create]
  end
  resources :likes, only: [:destroy]

  post 'games/:id/wish', to: "wishes#create", as: :wish
  post 'tracking', to: "games#tracking", as: :tracking
  get '/dashboard', to: "pages#dashboard", as: :dashboard
  get 'games/:id/game_alike', to: "games#game_alike", as: :game_alike
end

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(0deg,rgba(0,0,0,0.6) 50%,rgba(0,0,0,.6) 100%),radial-gradient(50% 120%,rgba(0,0,0,0.2) 50%,rgba(0,0,0,0.5) 100%), url(https://educayjuega.files.wordpress.com/2017/04/videojuegos-lista-time-1.jpg);">
    <div class="banner-content">
      <h1>GAMERCouch</h1>
      <p>Find the right game for you now</p>


      <form action="/tracking" method="POST" class="form-new-games">
          <select name="tracking[]" class="select2" placeholder="What's your favorite games ?" multiple="multiple" placeholder="select your games" allowClear: true>
            <% @games.each do |game| %>
              <option value="<%= game.id %>" ><%= game.name %></option>
            <% end %>
            <input type="submit" value="Find new games !" class= "home-button" >
          </select>
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
            <!-- <p class="sub-message">Enter the games you like</p> -->
      </form>

    </div>


</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_form.html.erb
<%= simple_form_for([ game, comment ], remote: true) do |form| %>
  <%= form.input :content, as: :text, placeholder: 'Write a comment' %>
  <%= form.submit "add a comment", class: "btn btn-primary" %>
<% end %>

app/views/shared/_form_comment_index.html.erb
<%= simple_form_for([ game, comment ], remote: true) do |form| %>
  <%= form.input :content, as: :text, placeholder: 'Write a comment' %>
  <%= hidden_field_tag "from", params[:action] %>
  <%= form.submit "add a comment", class: "btn btn-danger" %>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to games_path, class: "navbar-brand" do %>
    <%= image_tag "pad.png" %>
    <% end %>

  <p class="nav-site-title">GAMERCouch</p>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to "YOUR COUCH", dashboard_path, class: "add-game-button" %>
      </li>
        <!--<li class="nav-item">
          <%= link_to "Add a game", "#", class: "add-game-button" %>
        </li>-->
        <li class="nav-item dropdown">
          <% if current_user.avatar.blank? %>
          <%= image_tag "https://www.weekend-esprithautsdefrance.com/sites/picardiev3/themes/picardiev3/img_v2/user-default.jpg", class: "avatar-bordered", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
          <%= cl_image_tag current_user.avatar, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_way.html.erb
<div class="way-to-go">
  <div class="home-site-card">
    <%= image_tag "heart2.png",width: "100px",class: "left" %>
    <h2>You tell us your favorite games</h2>
  </div>
  <div class="home-site-card arrow"><i style="font-size: 100px" class="fas fa-arrow-right"></i></div>
  <div class="home-site-card">
    <%= image_tag "8da302a19e.png",width: "100px",class: "right"%>
    <h2 class="text-center">We give you the perfect game<br>according to your taste</p>
  </div>
</div>