config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  devise_scope :user do
    authenticated :user do
      root to: 'pages#home'
    end

    unauthenticated :user do
      root to: "devise/sessions#new"
    end
  end

  # root to: get 'sign_in', :to =>

  # devise_scope :user do
  #   get "/users/sign_in" => "registrations#new"
  # end

  #   root to: "devise/sessions#new"
   # root to:
  # root to: 'devise/registrations#new'

  resources :games, only: [:show, :index] do
    resources :comments, only: :create

    resources :likes, only: [:create]
  end
  resources :likes, only: [:destroy]

  post 'games/:id/wish', to: "wishes#create", as: :wish
  post 'tracking', to: "games#tracking", as: :tracking
  get '/dashboard', to: "pages#dashboard", as: :dashboard
  get 'games/:id/game_alike', to: "games#game_alike", as: :game_alike
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :likes, dependent: :destroy
  has_many :wishes, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :users, through: :likes
  has_many :liked_users, through: :likes, source: :user
  validates :name, presence: true, allow_blank: false
  validates :platform, presence: true
  mount_uploader :photo, PhotoUploader

  include PgSearch
  pg_search_scope :search_all,
    against: [:name, :year, :category, :platform],
    using: {
      tsearch: { prefix: true }
    }

  def match(user)
    users = Like.where("game_id= ?", self.id).pluck(:user_id)
    if !users.empty?
      other_sql = ActiveRecord::Base.connection.execute("SELECT games.id FROM games
                                                         JOIN likes ON games.id = likes.game_id
                                                         WHERE likes.user_id IN (#{users.join(",")})").values.flatten
    else
      other_sql = []
    end
    my_sql = ActiveRecord::Base.connection.execute("SELECT games.id FROM games
                                                    JOIN likes ON games.id = likes.game_id
                                                    WHERE likes.user_id = #{user.id}").values.flatten
    @matchings = other_sql.map { |g_id| Game.find(g_id) } & my_sql.map{ |g_id| Game.find(g_id) }
    @matchings.reject { |instance| instance == self }
    hash = {}
    @matchings.each do |jeu|
      hash[jeu] = jeu.likes.where(user_id: self.users).size.fdiv(self.likes.size) * 100
    end
    return hash = hash.sort_by { |game, score| score }.reverse
  end

  def three_most_liked
    liked_games = []
    users.each do |user|
      user.likes.each do |like|
        liked_games << like.game
      end
    end
    counts = Hash.new(0)
    liked_games.each { |name| counts[name] += 1 }
    result_inverse = counts.sort_by { |_key, value| value }.reverse
    r = result_inverse.reject { |game| game[0] == self }
    result_top_3 = r.first(3).map { |result| result[0] }
  end

def matching_score(user)
  total = []
  result = 0
  n = 0
  if !self.nil?
    self.match(user).each do |game|
      total << game[1]
    end
    total.sort.each do |score|
      n += 1
      result += score * n
    end
    a = (1..n).sum
    a == 0 ? result : (result / a).round(0)
    end
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  skip_after_action :verify_policy_scoped, only: [:index, :tracking]
  skip_after_action :verify_authorized


  def index
    if params[:sort] == "like"
      @games = Game.order("like_count DESC")
    elsif params[:sort] == "comment"
      @games = Game.order("comment_count DESC")
    else
      @games = Game.where.not(id: current_user.liked_games.pluck(:id))
      @games = @games.sort { |a, b| a.matching_score(current_user) <=> b.matching_score(current_user) }.reverse
    end

    if params[:search_query].present?
      @games = @games.search_all(params[:search_query])
    end
  end

  def show
    @game = Game.find(params[:id])
    authorize @game
    @comment = Comment.new
  end

  def tracking
    if params[:tracking]
    @games = Game.find(params[:tracking])
    @user = current_user
    @games.each do |game|
      authorize game
      @like = Like.new(game_id: game.id, user_id: @user.id)
      @like.save
    end
      redirect_to games_path
    else
      redirect_to root_path
    end
end

  def game_alike
    @game = Game.find(params[:tracking].to_i)
    authorize @game
    @three_most_liked_games = @game.three_most_liked
  end
end

app/views/games/_card_index.html.erb
<div class="card-product-index">

  <div class="card-product-index-left">
      <div class="card-product-index-img">
      <% if game.photo.present? %>
        <%= cl_image_tag game.photo, class: "img" %>
      <% else %>
        <%= image_tag "loading.png", class: "img" %>
      <% end %>
    </div>



    <div class="card-product-infos" id="game-<%= game.id %>">

      <h1 class="title"><strong><%= "#{game.name.upcase} (#{game.year})"%></strong></h1>

      <div class="platform"><h1><%= game.platform[0..75] %></h1></div>

      <div class="reaction">
          <!-- comments -->
          <div class="link-cursor">
            <div class="click-comment" data-game-id="<%= game.id %>">

              <% if game.comments.pluck(:user_id).include?(current_user.id) %>
                <i class="fas fa-comments"></i>
              <% else %>
                <i class="far fa-comments"></i>
              <% end %>(<%= game.comments.length %>)

            </div>
          </div>
          <!-- likes -->
          <div id="like-<%= game.id %>" class="link-cursor">
            <%= render "games/like", game: game %>
          </div>
          <!-- recommandations -->
      </div>

    </div>
    <%= link_to "", game_path(game), class: 'absolute-link' %>
  </div>
  <div class="right right-flex">
    <% game_scores = game.match(current_user).first(3) %>
    <% if !game_scores.present? %>
      <h2>No match found</h2>
    <% else %>
      <% score = game.matching_score(current_user) %>
      <% if !score.nil? %>
        <% if score <= 25 %>
          <% class_name = "badder" %>
        <% elsif score < 50 %>
          <% class_name = "less-bad" %>
        <% elsif score < 75 %>
          <% class_name = "good" %>
        <% elsif score <= 99 %>
          <% class_name = "very-good" %>
        <% else %>
          <% class_name = "perfect" %>
        <% end %>
      <% end %>


      <div id="match-score" class="<%= class_name %>">
        <div style="padding-left: 12px;">
          <%= "#{game.matching_score(current_user)}"%>
          <span class="match-score-percent">%</span></%>
        </div>

      </div>
      <div class="score-details">
          <a style="color:gray !important;font-weight: 700" class="right right_choice" data-game-id="<%= game.id %>" href="#">Details</a>
        </div>
    <% end %>
  </div>
</div>


<div class="card-product-index-comment">
  <div class="collapse" id="collapseGame<%= game.id %>">
      <% game.comments.each do |comment| %>
        <div class = "comment-content">
          <%= render 'games/comment_content', comment: comment %>
        </div>
      <% end %>
  </div>
</div>

<div class="recommandation-index hidden" data-game-id="<%= game.id %>" >
  <p>The others games they like :</p>
  <% game.three_most_liked.each do |like_game| %>
    <li><%= like_game.name %></li>
  <% end %>
</div>

<div class="match-index hidden" data-game-id="<%= game.id %>">
  <ul>
    <% if !game.match(current_user).empty? %>
      <% game.match(current_user).first(3).each do |game, score|%>
        <li>


          <div class="mini-card">

          <div class="mini-card-photo">
            <% if game.photo.present? %>
              <%= cl_image_tag game.photo, class: "img-mini" %>
            <% else %>
              <%= image_tag "loading.png", class: "img-mini" %>
            <% end %>
          </div>

          <div class="mini-card-title-infos">
            <div class="mini-card-title">
              <p><%= link_to game.name, game_path(game) %></p>
            </div>
              <div class="mini-card-score">
                <p class="matching-percent">
                  <strong><%= "#{score.round(1)} %"%> </strong> <%= "of players who played "%> <strong> <%= "#{game.name}"%> </strong> <%= "loved this"%> </%>
                </p>
              </div>
          </div>

          </div>


        </li>
      <% end %>
    <% else %>
      <h6>No matching found... Doesnt mean you won't like it but we can't say if it will fit your taste !</h6>
    <% end %>
  </ul>
</div>

<div class = "comment-index hidden" data-game-id="<%= game.id %>">
  <p> <strong> <% d = Date.today %> <%= d.strftime("%d/%b/%Y") %>
   ---
   <% game.comments.each do |comment| %>
     <%= comment.user.username %>
     <% if comment.user.avatar.blank? %>
        <%= image_tag "https://www.weekend-esprithautsdefrance.com/sites/picardiev3/themes/picardiev3/img_v2/user-default.jpg", class: "avatar-bordered", class: "avatar-bordered" %>
      <% else %>
        <%= cl_image_tag comment.user.avatar, class: "avatar-bordered"%>
      <% end %>
          </strong>
        </p>
    <p><%= comment.content %></p>
  <% end %>
</div>

app/views/games/_card_show.html.erb
<div class="card-product-show">
  <div class="card-product-top">
    <div id="big-image">
      <% if @game.photo.present? %>
        <%= cl_image_tag @game.photo %>
      <% else %>
        <%= image_tag "loading.png" %>
      <% end %>
    </div>


    <div class="card-product-infos">
      <div class="d-flex justify-content-between align-items-start">
        <h2 class="text-center"><%= @game.name %> </h2>
        <!-- <p>(<%= @game.year %>)</p> -->
        <div class="d-flex justify-content-center">
          <div class="add-wish ">
            <%= link_to "Add to wishlist", wish_path(@game), method: :post,class: "show-button-wishlist"  %>
          </div>
        </div>
      </div>
      <p> <%= @game.category %></p>
      <p><%= @game.platform %></p>
      <%if @game.likes.pluck(:user_id).include?(current_user.id) %>
        <p><i class="fas fa-heart"></i></p>
      <% end %>

      <div class="card-product-description">
        <% if !@game.description.nil? %>
          <p class="text-justify"><%= @game.description[0..400]+"..." %></p>
        <% end %>
      </div>
      <div class="d-flex justify-content-end pr-3">
        <%= link_to "Go back", games_path, class: "lien-goback" %>
      </div>
    </div>
  </div>

  <div class="carousel">
    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
      <div class="carousel-inner">
        <div class="carousel-item active">
        <% if @game.photo.present? %>
          <%= cl_image_tag "https://#{@game.screens[0]}",class: "d-block w-100" %>
        <% else %>
          <%= image_tag "loading.png" %>
        <% end %>
      </div>
      <div class="carousel-item">
        <% if @game.photo.present? %>
          <%= cl_image_tag "https://#{@game.screens[1]}",class: "d-block w-100" %>
        <% else %>
          <%= image_tag "loading.png" %>
        <% end %>
      </div>
      <div class="carousel-item">
        <% if @game.photo.present? %>
          <%= cl_image_tag "https://#{@game.screens[2]}",class: "d-block w-100" %>
        <% else %>
          <%= image_tag "loading.png" %>
        <% end %>
      </div>
    </div>
  </div>

  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
  <span aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>

</div>

app/views/games/_comment_content.erb
<div class = "comment-content">
     <strong>
<% if comment.user.avatar.blank? %>
          <%= image_tag "https://www.weekend-esprithautsdefrance.com/sites/picardiev3/themes/picardiev3/img_v2/user-default.jpg", class: "avatar-bordered" %>
          <% else %>
          <%= cl_image_tag comment.user.avatar, class: "avatar-bordered"%>
          <% end %>
   <%= comment.user.username %></strong>
  <p class="comment-content-description"> <% d = comment.created_at %> <%= d.strftime("%b %-d %Y") %>
   <br>

      </p>
  <p class="comment-content-description"><%= comment.content %></p>
</div>

app/views/games/_form.html.erb
<%= simple_form_for([ game, comment ], remote: true) do |form| %>
  <%= form.input :content, as: :text, placeholder: 'Write a comment', label: false %>
  <%= form.submit "Add a new comment", class: "submit-comment-show" %>
<% end %>

app/views/games/_like.html.erb
<h4>
  <div class="click-like" data-game-id="<%= game.id %>">
    <% like = game.likes.where(user: current_user).first %>
    <% if like %>
      <%= link_to like_path(like), method: :delete, remote: true do %>
        <i class="fas fa-heart"></i>
        <span class="counterlike">(<%= game.like_count %>)</span>
      <% end %>
    <% else %>
      <%= link_to game_likes_path(game), method: :post, remote: true do %>
        <i class="far fa-heart"></i>
        <span class="counterlike">(<%= game.like_count %>)</span>
      <% end %>
    <% end %>
  </div>
</h4>

app/views/games/index.html.erb
<div class="container">

  <div class="<%= current_user.likes.count < 5 ? 'search-bar-careful-one' : 'search-bar' %>">
    <%= form_tag games_path, method: :get do %>
      <%= hidden_field_tag :sort, params[:sort] %>
      <%= text_field_tag :search_query,
      params[:search_query],
      class: "form-control",
      placeholder: "Search on GameCouch "
      %>
  <% end %>
  </div>
  <div class="row">
    <div class="col-2">
      <div class="row">
      <div class="lateral-button">
          <div class="col-12 p-2">
            <%= link_to "Games meant for you", games_path %>
          </div>
          <div class="col-12 p-2">
            <%= link_to "Sort by like", games_path(sort: "like", search_query: params[:search_query]) %>
        </div>
          <div class="col-12 p-2">
            <%= link_to "Sort by comment", games_path(sort: "comment", search_query: params[:search_query])%>
          </div>
        </div>
      </div>
    </div>
    <div class="col-10">








      <% @games.each do |game| %>
        <div id="card-<%= game.id %>">
          <%=render "card_index", game: game %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/games/right_choice.html.erb
<div class="container">
  <h1>Does <%= @game.name %> match your taste ?</h1>
 <% @matching_games.each do |game| %>
   <%= render "right_choice", game: game%>
  <% end %>

  <%= link_to "Go back to index", games_path  %>
</div>

app/views/games/show.html.erb
<% content_for :meta_title, "#{@game.name} is on #{DEFAULT_META["meta_product_name"]}" %>
<% content_for :meta_description, @game.description %>

<body>


<% if !@game.photo.present? %>
  <% content_for :meta_image, image_path("loading.png")  %>
<% else %>
  <% content_for :meta_image, cl_image_path(@game.photo) %>
<% end %>

<div class="container">
  <div class="row justify-content-center d-flex">
    <div class="show-and-comment">
      <%=render "games/card_show" %>
    </div>
    <div class="comment-block">
      <%= render 'games/form', game: @game, comment: @comment %>
      <div id="comments" class="text-justify">
        <% myTab = Array.[] %>
        <% @game.comments.each do |comment| %>
          <% myTab << comment %>
        <% end %>
        <% myTab.reverse!%>
        <% myTab.each do |element| %>
          <%= render 'games/comment_content', comment: element %>
        <% end %>
      </div>
    </div>
  </div>
</div>

</body>